version: '3.8'

services:
  server:
    build: .
    container_name: chat_server
    ports:
      - "12345:12345"
    command: ./server
    networks:
      chat_net:
        ipv4_address: 172.28.0.2

  client1:
    build: .
    container_name: client1
    stdin_open: true
    tty: true
    networks:
      chat_net:
        ipv4_address: 172.28.0.3
    command: ./client 172.28.0.2 12345

  client2:
    build: .
    container_name: client2
    stdin_open: true
    tty: true
    networks:
      chat_net:
        ipv4_address: 172.28.0.4
    command: ./client 172.28.0.2 12345

networks:
  chat_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16